return {
    ActiveStage = 8, -- 5: pets, 6: capture, 7: data, 8: tutorial/UI
    MaxPlayers = 6,
    TargetNights = 5, -- 5밤, 약 37분 (첫 낮 6분 + 낮 4분 x4 + 밤 3분 x5)
    FirstDaySeconds = 360,
    DaySeconds = 240,
    NightSeconds = 180,
    WarningSeconds = 75, -- 맵이 넓어서 멀리 나간 사람이 돌아올 시간
    StudioTimeScale = 1, -- Studio only: 5 = short functional test, not balance test
    -- Studio 에서 어떻게 시작할지: "Both" = 로비 캠프에서 시작해 수레를 타면 같은 서버의 원정 맵으로 (실제 게임과 같은 흐름)
    --                              "Expedition" = 로비 없이 바로 원정 (원정만 빨리 시험할 때)
    StudioMode = "Both",
    StartDelay = 4, -- 들어와서 원정 시작까지 (30초 안에 놀기 시작)
    ResultSeconds = 20,
    DawnSeconds = 4,
    TickSeconds = 0.2,
    StateInterval = 0.5,
    CoreHP = 1000,
    TowerDamageScale = 0.7, -- tuning hypothesis: pets should supply mobile damage
    InteractionRange = 13,
    InteractionCooldown = 0.35,
    SpearRange = 11, -- 손에 든 도구의 공격·채집 거리
    SpearDamage = 24,
    SpearCooldown = 0.55,
    HarvestDamage = 25, -- 채집 기본 피해 (도구 배율을 곱한다, ItemConfig)
    EatCooldown = 0.8,
    SnackRange = 26, -- 간식을 들고 쓰면 이 거리 안의 다친 내 펫을 회복
    PickupRadius = 5,
    DepositRadius = 11,
    KeepBerries = 5, -- 창고에 넣을 때 가방에 남기는 열매 (먹을 것)
    CarryCapacity = 60, -- 가방 없을 때 (가방은 ItemConfig)
    DeathDropFraction = 0.3,
    RespawnSeconds = 4,
    EnemyLimit = 35,
    PathInterval = 1.5,
    PathJobsLimit = 2,
    RunnerLeash = 32,
    RepairFraction = 0.3,
    NightRepairMultiplier = 2,
    DropLifetime = 45,
    DropLimit = 180,
    FXLifetime = 0.12,
    -- 배고픔 (가볍게): 약 7분에 100 → 0. 0이면 체력이 조금씩 닳지만 StarveFloor 아래로는 안 내려간다
    HungerMax = 100,
    HungerDecay = 0.24,
    StarveDamage = 3,
    StarveInterval = 3,
    StarveFloor = 20,
    RespawnHunger = 50,
    DayClock = 13,
    NightClock = 0,
}
